services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    command: sh -c "npm rebuild bcrypt && npm start"
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
